services:
  nodo1:
    build:
      context: ./servidor-base
    environment:
      - NODE_NAME="Nodo A"
      - PUERTO_NODOS=3000
    networks:
      - red-cluster

  nodo2:
    build:
      context: ./servidor-base
    environment:
      - NODE_NAME="Nodo B"
      - PUERTO_NODOS=3000
    networks:
      - red-cluster

  nodo3:
    build:
      context: ./servidor-base
    environment:
      - NODE_NAME="Nodo C"
      - PUERTO_NODOS=3000
    networks:
      - red-cluster

  nodo4:
    build:
      context: ./servidor-base
    environment:
      - NODE_NAME="Nodo D"
      - PUERTO_NODOS=3000
    networks:
      - red-cluster

  nodo5:
    build:
      context: ./servidor-base
    environment:
      - NODE_NAME="Nodo E"
      - PUERTO_NODOS=3000
    networks:
      - red-cluster

  balanceador:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodo1
      - nodo2
      - nodo3
      - nodo4
      - nodo5
    networks:
      - red-cluster

networks:
  red-cluster:
    driver: bridge