events {
    # Bloque obligatorio en la configuración general
}

http {
    # Define el grupo de servidores que recibirá las solicitudes
    upstream cluster_aplication {
        least_conn;
        server nodo1:3000 weight=3;
        server nodo2:3000 weight=2;
        server nodo3:3000 weight=1;
        server nodo4:3000;
        server nodo5:3000;
    }

    server {
        # Puerto en el cual escuchará NGINX
        listen 80;

        location / {
            # Enviar cada solicitud al grupo definido anteriormente
            proxy_pass http://cluster_aplication;

            # Conservar la información de la solicitud original
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Si uno de los nodos no responde, intenta con el siguiente
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }
    }
}